env:
  global:
    - LC_CTYPE=en_US.UTF-8

matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9.2
      script:
        - set -o pipefail
        - xcodebuild test -workspace DIKit.xcworkspace -scheme DIGenKit -configuration Release ENABLE_TESTABILITY=YES | xcpretty -c
        - xcodebuild build -workspace DIKit.xcworkspace -scheme DIKit -configuration Release | xcpretty -c
        - xcodebuild build -workspace DIKit.xcworkspace -scheme DIKit -configuration Release -sdk iphonesimulator | xcpretty -c
        - xcodebuild build -workspace DIKit.xcworkspace -scheme DIKit -configuration Release -sdk watchsimulator | xcpretty -c
        - xcodebuild build -workspace DIKit.xcworkspace -scheme DIKit -configuration Release -sdk appletvsimulator | xcpretty -c
    - os: osx
      language: objective-c
      osx_image: xcode9.4
      script:
        - set -o pipefail
        - xcodebuild test -workspace DIKit.xcworkspace -scheme DIGenKit -configuration Release ENABLE_TESTABILITY=YES | xcpretty -c
        - xcodebuild build -workspace DIKit.xcworkspace -scheme DIKit -configuration Release | xcpretty -c
        - xcodebuild build -workspace DIKit.xcworkspace -scheme DIKit -configuration Release -sdk iphonesimulator | xcpretty -c
        - xcodebuild build -workspace DIKit.xcworkspace -scheme DIKit -configuration Release -sdk watchsimulator | xcpretty -c
        - xcodebuild build -workspace DIKit.xcworkspace -scheme DIKit -configuration Release -sdk appletvsimulator | xcpretty -c
    - os: osx
      language: objective-c
      osx_image: xcode10
      script:
        - set -o pipefail
        - xcodebuild test -workspace DIKit.xcworkspace -scheme DIGenKit -configuration Release ENABLE_TESTABILITY=YES | xcpretty -c
        - xcodebuild build -workspace DIKit.xcworkspace -scheme DIKit -configuration Release | xcpretty -c
        - xcodebuild build -workspace DIKit.xcworkspace -scheme DIKit -configuration Release -sdk iphonesimulator | xcpretty -c
        - xcodebuild build -workspace DIKit.xcworkspace -scheme DIKit -configuration Release -sdk watchsimulator | xcpretty -c
        - xcodebuild build -workspace DIKit.xcworkspace -scheme DIKit -configuration Release -sdk appletvsimulator | xcpretty -c
    - os: osx
      language: generic
      osx_image: xcode9.2
      script:
        - swift build
        - swift test
    - os: osx
      language: generic
      osx_image: xcode9.4
      script:
        - swift build
        - swift test
    - os: osx
      language: generic
      osx_image: xcode10
      script:
        - swift build
        - swift test

notifications:
  email: false
